# docs ####

#' @title Stateful Tile Iterator
#' @name tileIterator
#' @description
#' Create a stateful iterator that maintains an internal position and yields batches
#' of tiles on demand. Uses closures for serializable stateful behavior without
#' external dependencies. Useful for streaming processing, memory-constrained
#' environments, or when you want to process tiles in smaller chunks.
#'
#' This is a structure that works with any underlying `tilePlan`. `tileGroup`
#' is also accepted when an `$active` group has already been set, or a group
#' is specified via `tileIterator(active_group)`
#'
#' *Note that `tileIterator` contains its own state and an independent copy of it
#' cannot be generated by assigning to a new variable.* Instead, use either the
#' `$copy()` method or [iterSplit()].
#'
#' @section Methods:
#' * `[]`/`[]<-` or `$tiles`/`$tiles<-`
#'   * get or set a `tilePlan` or `tileGroup` (with `$active` set). `[]` notation is just shorthand.
#' * `$position`/`$position<-`
#'   * get and set current position of iterator
#' * `$batch_size`/`$batch_size<-`
#'   * get and set batch size.
#' * `$bound`/`$bound<-`
#'   * get and set iteration tile index bounds. This is a numeric vector of 2 (min, max)
#' * `$next_batch()`/`$next_indices()`
#'   * get next batch or just their tile indices.
#'     * Has an `advance` param (default = `TRUE`) that advances iterator position.
#'     * When there are no more tiles, gracefully returns empty `list`
#' * `$peek_batch()`/`$peek_indices`
#'   * Get next batch or indices without advancing position. When there are no more tiles, gracefully returns empty `integer`
#' * `$has_next`
#'   * Return `logical` if there are still tiles left to iterate through (if `position` < `max(bound)`). Useful for `while` looping.
#' * `$total_tiles`
#'   * Return total number of tiles in `bound`
#' * `$remaining`
#'   * Return number of remaining indices to traverse.
#' * `$progress`
#'   * Return current percentage of `position` traversal across `bound`
#' * `$reset()`
#'   * Reset position to 1 before the lower `bound`
#' * `$copy()`
#'   * Create a new `tileIterator` with the same settings (deep copy)
#'
#' @section Usage Patterns:
#' * Stream processing large datasets
#' * Memory-constrained batch processing
#' * Progressive/incremental analysis
#' * Checkpoint and resume workflows
#' * Parallel processing with foreach
#'
#' @param tiles A tile* object
#' @param batch_size Integer. Number of tiles to return per call to next_batch()
#' @param bound numeric, length of 2. Min and max indexing bounds through which
#' to iterate. Default is `c(1, length(tiles)) `
#' @param position numeric. Set the starting position of the iterator. Default
#' is 0.
#' @param active_group character (optional). Only used when `tiles` is a `tileGroup`.
#' Syntactic sugar for setting the active group of the `tileGroup` before using it.
#' @returns A tileIterator function with attached methods
#' @seealso [tileIterator-class]
#' @export
#' @examples
#' # Create a spatial tile iterator
#' tp <- tilePlan("spatial")
#' ext(tp) <- c(0, 100, 0, 100)
#' length(tp) <- 16
#'
#' # Create a iterator that processes 3 tiles at a time
#' iter <- tileIterator(tp, batch_size = 3)
#'
#' # Check status
#' iter
#' iter$has_next
#' iter$remaining
#' iter$progress
#'
#' # Get next batch
#' batch1 <- iter$next_batch()
#' length(batch1) # 3 tiles
#'
#' # Check updated status
#' iter$progress # position has advanced
#'
#' # Peek at next batch without advancing
#' peek <- iter$peek_batch()
#' peek
#' iter$position # unchanged
#'
#' # serialize and unserialize, preserving state
#' temp <- tempfile()
#' saveRDS(iter, temp)
#' rm(iter)
#' iter <- readRDS(temp)
#'
#' # Next batch of indices
#' iter$next_indices()
#'
#' # Peek next batch of indices
#' iter$peek_indices()
#'
#' # Process all remaining batches
#' while (iter$has_next) {
#'     batch <- iter$next_batch()
#'     cat("Processing batch of", length(batch), "tiles\n")
#' }
#'
#' # Reset and try different batch size
#' iter$reset()
#' iter$batch_size <- 5
#'
#' # Apply function across all batches
#' while (iter$has_next) {
#'     batch <- iter$next_batch()
#'     cat("Processing batch of", length(batch), "tiles\n")
#' }
#'
#' # tileIterator with tileGroup
#' tg <- tileGroup(tp, groups = list(
#'     "g1" = c(2, 4, 6, 8, 10, 12, 14, 16),
#'     "g2" = 1:16
#' ))
#'
#' tg$active <- "g1"
#' iter <- tileIterator(tg, batch_size = 3)
#' iter
#' iter$next_batch()
#'
#' # iterator splitting
#' siter <- iterSplit(iter, n = 2)
#' siter
NULL


setMethod("initialize", signature("tileIterator"), function(.Object, ...) {
    # do not allow re-initialization after closures are setup
    if (length(.Object@funs) > 0) {
        checkmate::assert_list(.Object@funs, types = "function")
        return(.Object)
    }

    tp <- NULL
    bound <- c(1L, 1L)
    batch_size <- 1L
    position <- min(bound) - 1L # the last tile that was finished

    # private methods ----------------------------------------------------- #
    prefix <- "tileIterator: "

    .guard_pos_bound <- function(x = NULL) {
        x <- x %||% position
        if (x < (bound[1L] - 1) || x > bound[2L]) {
            stop(sprintf(
                "%s `position` (%d) must be within `bound` (between %d and %d)\n",
                prefix, position, bound[1L], bound[2L]
            ), call. = FALSE)
        }
    }

    .guard_tp <- function(x = NULL) {
        x <- x %||% tp
        if (is.null(x)) {
            stop(prefix, "No underlying `tilePlan`. Assign one with `[]`<-\n", call. = FALSE)
        }
        if (!inherits(x, c("tilePlan", "tileGroup"))) {
            stop("`tileplan` must be tilePlan or tileGroup, got: ", class(x))
        }
        if (inherits(x, "tileGroup") && !.has_active(x)) {
            stop("tileGroup requires an active group. Set with $active <- \"group_name\"")
        }
    }

    .guard_batch_size <- function(x = NULL) {
        x <- x %||% batch_size
        if (x < 1L) {
            stop(sprintf(
                "%s `batch_size` (%d) must be at least 1\n",
                prefix, x
            ), call. = FALSE)
        }
    }

    .guard_bound <- function(x = NULL) {
        x <- x %||% bound
        if (length(x) != 2L) {
            stop(prefix, "`bound` must be 2 numbers (start index, end index)\n", call. = FALSE)
        }
        if (x[2L] < x[1L]) {
            stop(prefix, "`bound` end index must be equal to or greater than start index\n", call. = FALSE)
        }
        if (all(x == c(1L, 1L))) {
            warning(prefix, "`bound` is at default = c(1, 1). Set a different one with `$bound <-`", call. = FALSE)
        }
    }

    .extract_fun <- function(x, i) {
        if (inherits(x, "tilePlan")) {
            return(x[i])
        }
        if (inherits(x, "tileGroup")) {
            if (!.has_active(x)) {
                stop("tileIterator with tileGroup requires an active group. Set with $active <- \"group_name\"")
            }
            return(x[i])
        }
        stop("Unsupported object type: ", class(x))
    }

    # public methods ----------------------------------------------------- #
    funs <- list()

    funs$bound <- function() {
        bound
    }

    funs$set_bound <- function(x) {
        .guard_bound(x)
        bound <<- as.integer(x)
        invisible(.Object)
    }

    funs$position <- function() {
        position
    }

    funs$set_position <- function(x) {
        new_pos <- as.integer(x)[1L]
        .guard_pos_bound(new_pos)
        position <<- new_pos
        invisible(.Object)
    }

    funs$reset <- function() {
        position <<- min(bound) - 1L
        invisible(.Object)
    }

    funs$total_tiles <- function() {
        diff(bound) + 1L
    }

    funs$tiles <- function() {
        tp
    }

    funs$set_tiles <- function(x) {
        .guard_tp(x = x)
        tp <<- x
        invisible(.Object)
    }

    funs$has_next <- function() {
        .guard_pos_bound()
        position < bound[[2L]]
    }

    funs$batch_size <- function() {
        batch_size
    }

    funs$set_batch_size <- function(x) {
        x <- as.integer(x)[[1L]]
        .guard_batch_size(x)
        batch_size <<- x
        invisible(.Object)
    }

    funs$next_batch <- function(advance = TRUE) {
        # get indices
        indices <- funs$next_indices(advance = FALSE)
        if (length(indices) == 0L) {
            return(list())
        }
        start_idx <- head(indices, 1L)
        end_idx <- tail(indices, 1L)
        # extract tiles
        tiles <- .extract_fun(tp, indices)

        # Advance position if requested
        if (advance) {
            position <<- end_idx
        }

        # Attach batch metadata
        attr(tiles, "batch_start") <- start_idx
        attr(tiles, "batch_end") <- end_idx
        attr(tiles, "batch_size") <- length(indices)
        attr(tiles, "iterator_position") <- position

        return(tiles)
    }

    funs$peek_batch <- function() {
        funs$next_batch(advance = FALSE)
    }

    funs$next_indices <- function(advance = TRUE) {
        .guard_tp()
        .guard_pos_bound()
        .guard_batch_size()
        checkmate::assert_logical(advance, len = 1L)
        if (!funs$has_next()) {
            return(integer()) # return empty integer when no more
        }

        start_idx <- position + 1L
        end_idx <- min(position + batch_size, bound[2L])
        idx <- start_idx:end_idx

        # Advance position if requested
        if (advance) {
            position <<- end_idx
        }

        idx
    }

    funs$peek_indices <- function() {
        funs$next_indices(advance = FALSE)
    }

    funs$remaining <- function() {
        max(0L, bound[2L] - position)
    }

    funs$progress <- function() {
        round(100 * ((position - bound[1L] + 1L) / funs$total_tiles()), digits = 2)
    }

    funs$copy <- function() {
        new_iter <- new("tileIterator")
        new_iter$bound <- bound
        new_iter$batch_size <- batch_size
        if (!is.null(tp)) {
            new_iter$tiles <- tp
        }
        new_iter$position <- position
        new_iter
    }

    # attach public closures
    .Object@funs <- funs
    # return
    .Object
})

#' @export
.DollarNames.tileIterator <- function(x, pattern) {
    c(
        # attributes
        "position", "bound", "batch_size", "tiles",
        # computed properties
        "total_tiles", "remaining", "has_next", "progress",
        # methods
        "next_batch()", "peek_batch()", "next_indices()", "peek_indices",
        "reset()", "copy()"
    )
}

#' @rdname tileIterator
#' @param x `tileIterator`
#' @param name Name of method or attribute to access (See Methods section)
#' @export
setMethod("$", signature("tileIterator"), function(x, name) {
    switch(name,
        # get
        "position" = x@funs$position(),
        "bound" = x@funs$bound(),
        "batch_size" = x@funs$batch_size(),
        "tiles" = x@funs$tiles(),
        # computed properties
        "total_tiles" = x@funs$total_tiles(),
        "remaining" = x@funs$remaining(),
        "has_next" = x@funs$has_next(),
        "progress" = x@funs$progress(),
        # methods
        "next_batch" = x@funs$next_batch,
        "peek_batch" = x@funs$peek_batch,
        "next_indices" = x@funs$next_indices,
        "peek_indices" = x@funs$peek_indices,
        "reset" = x@funs$reset,
        "copy" = x@funs$copy
    )
})

#' @rdname tileIterator
#' @param value value to set for an attribute (See Methods section)
#' @export
setMethod("$<-", signature("tileIterator"), function(x, name, value) {
    switch(name,
        "position" = x@funs$set_position(value),
        "bound" = x@funs$set_bound(value),
        "batch_size" = x@funs$set_batch_size(value),
        "tiles" = x@funs$set_tiles(value)
    )
    x
})

#' @rdname hidden_docs
setMethod("show", signature("tileIterator"), function(object) {
    cat(sprintf("Object of class %s\n", class(object)))
    plist <- list(
        tiles = class(object@funs$tiles()),
        position = object@funs$position(),
        bound = sprintf("[%s]", toString(object@funs$bound())),
        batch_size = object@funs$batch_size(),
        progress = sprintf("%s%s", object@funs$progress(), "%"),
        remaining = object@funs$remaining()
    )
    GiottoUtils::print_list(plist)
})

#' @rdname bracket
#' @export
setMethod("[", signature("tileIterator", "missing", "missing", "missing"), function(x, ...) {
    x@funs$tiles()
})

#' @rdname bracket
#' @export
setMethod("[<-", signature("tileIterator", "missing", "missing", value = "ANY"), function(x, ..., value) {
    if (!inherits(value, c("tilePlan", "tileGroup"))) {
        stop("Value must be tilePlan or tileGroup, got: ", class(value))
    }
    if (inherits(value, "tileGroup") && !.has_active(value)) {
        stop("tileGroup requires an active group. Set with $active <- \"group_name\"")
    }
    x@funs$set_tiles(value)
    x
})

#' @rdname dim
#' @export
setMethod("length", signature("tileIterator"), function(x) {
    x@funs$total_tiles()
})


# factory ####

#' @rdname tileIterator
#' @export
tileIterator <- function(tiles = NULL, position = 0, bound = NULL, batch_size = 1, active_group = NULL) {
    checkmate::assert_integerish(position, len = 1L)
    checkmate::assert_integerish(bound, null.ok = TRUE, len = 2L)
    checkmate::assert_integerish(batch_size, len = 1L)
    checkmate::assert_character(active_group, null.ok = TRUE)
    ti <- new("tileIterator")
    if (!is.null(tiles)) {
        if (inherits(tiles, "tileGroup") && !is.null(active_group)) {
            tiles$active <- active_group
        }
        if (!inherits(tiles, c("tilePlan", "tileGroup"))) {
            stop("`tiles` must be tilePlan or tileGroup, got: ", class(tiles))
        }
        if (inherits(tiles, "tileGroup") && !.has_active(tiles)) {
            stop("tileGroup requires an active group. Set with $active <- \"group_name\"")
        }
        ti$tiles <- tiles
    }
    if (!is.null(bound)) {
        ti$bound <- bound
    } else if (!is.null(tiles)) {
        ti$bound <- c(1L, length(tiles))
    }
    ti$batch_size <- batch_size
    ti$position <- position
    ti
}

# iterSplit ####

#' @name iterSplit
#' @title Create multiple walkers from a single iterator
#' @description
#' Utility function to create multiple independent walkers for parallel processing.
#' Each iterator will have the same underlying iterator but independent state.
#'
#' @param tiles tileIterator object
#' @param n integer. Number of iterators to create
#' @param batch_size integer (optional). Assign a batch size for each iterator.
#'  If not provided, inherits same `batch_size` as source `tiles`.
#' @param distribute logical (default = `TRUE`). If `TRUE`, distribute tiles
#' evenly across iterators. Otherwise return multiple true copies.
#' @export
setMethod(
    "iterSplit", signature("tileIterator"),
    function(tiles, n, batch_size = NULL, distribute = TRUE, ...) {
        checkmate::assert_logical(distribute, len = 1L)
        checkmate::assert_integerish(batch_size, null.ok = TRUE, len = 1L, lower = 1L)
        checkmate::assert_integerish(n, len = 1L, lower = 1L)
        n <- as.integer(n)
        iters <- list()
        batch_size <- batch_size %||% tiles$batch_size

        if (!distribute) {
            # each iterator gets the same settings
            for (i in seq_len(n)) {
                iters[[i]] <- tileIterator(
                    tiles = tiles$tiles,
                    position = tiles$position,
                    bound = tiles$bound,
                    batch_size = batch_size
                )
            }
            return(iters)
        }

        # Distribute tiles evenly across workers
        rem <- tiles$remaining
        tiles_per_iter <- floor(rem / n)
        remainder <- rem %% n
        start_pos <- tiles$position # init position index

        if (n > rem) {
            warning(wrap_txtf(
                "More iterators (%d) than remaining tiles (%d).
            Creating %d iterators instead.", n, rem, rem
            ), call. = FALSE)
            n <- rem
        }

        for (i in seq_len(n)) {
            end_pos <- start_pos + tiles_per_iter
            if (remainder > 0L) {
                end_pos <- end_pos + 1L
                remainder <- remainder - 1L
            }
            b <- c(start_pos + 1L, end_pos)

            iters[[i]] <- tileIterator(
                tiles = tiles$tiles,
                position = start_pos,
                bound = b,
                batch_size = batch_size
            )
            start_pos <- end_pos
        }
        iters
    }
)
